export const REVIEWS_FETCH_START = 'REVIEWS_FETCH_START';
export const REVIEWS_FETCH_SUCCESS = 'REVIEWS_FETCH_SUCCESS';
export const REVIEWS_FETCH_FAIL = 'REVIEWS_FETCH_FAIL';
export const SEARCH_INPUT= 'SEARCH_INPUT';